name: Build project
on: [push]
jobs:

  buildProject:
    name: Build project
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'    
    
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-SpaceBall-WebGL
          restore-keys: |
            Library-SpaceBall-
            Library-

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/744153426878/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'teamapple@eighth-codex-340614.iam.gserviceaccount.com'  
            
      - uses: game-ci/unity-builder@v2.0.0-alpha-14
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL
          
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: build
          destination: 'www.spaceball.co.uk/build'         
          
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      
          